spring:
  application:
    name: spring-boot-caching
  cache:
    type: simple
    cache-names: books
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true